apiVersion: batch/v1
kind: Job
metadata:
  name: mo-updater
spec:
  backoffLimit: 4
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  template:
    spec:    
      volumes:
      - name: updater-cm
        configMap:
          name: updater-cm
          items:
            - key: values.command
              path: values.command                
      containers:
      - image: ghcr.io/mogenius/mogenius-updater:latest
        imagePullPolicy: Always
        name: mo-updater
        volumeMounts:
        - mountPath: /kubeconfig
          readOnly: true
          name: updater-cm
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      serviceAccount: mogenius-k8s-manager-service-account-app
      serviceAccountName: mogenius-k8s-manager-service-account-app
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30