apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  labels:
    type: nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: monfs.file.core.windows.net
    path: "/monfs/mogenius-dev-cluster"