browser:
  host: 127.0.0.1
  port: 8080

kubernetes:
  cluster_name: your-cluster-name
  own_namespace: punq
  run_in_cluster: true
  container_port: 8080

misc:
  stage: dev
  debug: false
  check_for_updates: 86400
  ignore_namespaces: ["kube-system"]