backend:
  host: 127.0.0.1
  port: 8080

frontend:
  host: 127.0.0.1
  port: 8081

kubernetes:
  ingress_host: localhost
  cluster_name: your-cluster-name
  own_namespace: punq
  run_in_cluster: true

misc:
  stage: prod
  debug: false
  check_for_updates: 86400
  ignore_namespaces: ["kube-system"]