apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-certificate
spec:
  secretName: my-certificate-secret
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  dnsNames:
  - example.com
  - www.example.com
  issuerRef:
    name: my-cluster-issuer
    kind: ClusterIssuer
