name: Build, Package, Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute make all
        run: make all

      - name: Package artefacts
        run: |
          for file in builds/*; do
            tar -czvf builds/$(basename "$file").tar.gz -C builds $(basename "$file")
          done
          ls -lisa builds

      # - name: Create Tag
      #   run: |
      #     VERSION=v$(grep "Ver" version/consts.go | awk -F "\"" {'print $2'})
      #     echo "$VERSION"
      #     git tag $VERSION
      #     git push --tags

      - name: Create release
        run: |
          VERSION=v$(grep "Ver" version/consts.go | awk -F "\"" {'print $2'})
          gh release create refs/tags/"$VERSION" --title "Release $VERSION" --repo mogenius/punq
        env:
          GH_TOKEN: ${{ secrets.PUNQ_TOKEN }}

      - name: Check if release exists
        run: |
          VERSION=v$(grep "Ver" version/consts.go | awk -F "\"" {'print $2'})
          gh release view "$VERSION" --repo mogenius/punq
        env:
          GH_TOKEN: ${{ secrets.PUNQ_TOKEN }}

      - name: Upload tarballs
        run: |
          VERSION=v$(grep "Ver" version/consts.go | awk -F "\"" {'print $2'})
          echo "$VERSION"
          ls -lisa builds
          for tarball in builds/*.tar.gz; do
            gh release upload "$VERSION" "$tarball" --repo mogenius/punq
          done
        env:
          GH_TOKEN: ${{ secrets.PUNQ_TOKEN }}

      - name: UPDATE BREW
        run: |
          VERSION=v$(grep "Ver" version/consts.go | awk -F "\"" {'print $2'})
          ./release.sh
          git config --global user.email "punq@mogenius.com"
          git config --global user.name "punq"
          git config --global credential.helper cache
          git add punq.rb
          git commit -m "$VERSION"
          git push
