name: Build, Package, Release

on:
  push:
    branches:
      - main
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute make all
        run: make all

      - name: Create Tag
        run: |
          VERSION=v$(grep "Ver" version/consts.go | awk -F "\"" {'print $2'})
          echo "$VERSION"
          git tag $VERSION
          git push --tags

      - name: Create release
        run: |
          VERSION=v$(grep "Ver" version/consts.go | awk -F "\"" {'print $2'})
          gh release create refs/tags/"$VERSION" --title "Release $VERSION" --repo mogenius/punq
        env:
          GH_TOKEN: ${{ secrets.PUNQ_TOKEN }}

      - name: Upload binaries
        run: |
          VERSION=v$(grep "Ver" version/consts.go | awk -F "\"" {'print $2'})
          echo "$VERSION"
          ls -lisa builds
          for build in builds/*; do
            gh release upload "$VERSION" "$build" --repo mogenius/punq
          done
        env:
          GH_TOKEN: ${{ secrets.PUNQ_TOKEN }}

      - name: Create release in another repo
        run: |
          VERSION=v$(grep "Ver" version/consts.go | awk -F "\"" {'print $2'})
          gh release create refs/tags/"$VERSION" --title "Release $VERSION" --repo mogenius/homebrew-punq
        env:
          GH_TOKEN: ${{ secrets.PUNQ_TOKEN }}

      - name: Check if release exists
        run: |
          VERSION=v$(grep "Ver" version/consts.go | awk -F "\"" {'print $2'})
          gh release view "$VERSION" --repo mogenius/homebrew-punq
        env:
          GH_TOKEN: ${{ secrets.PUNQ_TOKEN }}
      
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          file: Dockerfile-Operator
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            type=semver,pattern={{version}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Package artefacts
        run: |
          for file in builds/*; do
            tar -czvf builds/$(basename "$file").tar.gz -C builds $(basename "$file")
          done
          ls -lisa builds

      - name: Upload tarballs
        run: |
          VERSION=v$(grep "Ver" version/consts.go | awk -F "\"" {'print $2'})
          echo "$VERSION"
          ls -lisa builds
          for tarball in builds/*.tar.gz; do
            gh release upload "$VERSION" "$tarball" --repo mogenius/homebrew-punq
          done
        env:
          GH_TOKEN: ${{ secrets.PUNQ_TOKEN }}

      - name: UPDATE BREW
        run: |
          VERSION=v$(grep "Ver" version/consts.go | awk -F "\"" {'print $2'})
          ./release.sh
          git config --global user.email "mogenius-cli@mogenius.com"
          git config --global user.name "mogenius-cli"
          git config --global credential.helper cache
          git clone https://${{secrets.PUNQ_TOKEN}}@github.com/mogenius/homebrew-punq
          cd homebrew-punq
          cp ../punq.rb .
          git add .
          git commit -m "$VERSION"
          git push
        env:
          GH_TOKEN: ${{ secrets.PUNQ_TOKEN }}