name: Build, Package, Release

on:
  push:
    branches:
      - main
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      #
      # TODO: NPM RUN BUILD GOES HERE
      #
      - name: npm run build
        run: |
          mkdir ui/dist
          cp ui/index.html ui/dist/index.html

      - name: Execute make all
        run: make all

      - name: Create Tag
        run: |
          VERSION=v$(grep "Ver" version/consts.go | awk -F "\"" {'print $2'})
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "${{ env.VERSION }}"
          git tag ${{ env.VERSION }}
          git push --tags

      - name: Create release
        run: |
          gh release create refs/tags/${{ env.VERSION }} --title "Release ${{ env.VERSION }}" --repo mogenius/punq
        env:
          GH_TOKEN: ${{ secrets.PUNQ_TOKEN }}

      - name: Upload binaries
        run: |
          ls -lisa builds
          for build in builds/*; do
            gh release upload ${{ env.VERSION }} "$build" --repo mogenius/punq
          done
        env:
          GH_TOKEN: ${{ secrets.PUNQ_TOKEN }}

      - name: Create release in another repo
        run: |
          gh release create refs/tags/${{ env.VERSION }} --title "Release ${{ env.VERSION }}" --repo mogenius/homebrew-punq
        env:
          GH_TOKEN: ${{ secrets.PUNQ_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile-Operator
          context: .
          push: true
          tags: mogenius/punq:${{ env.VERSION }}

      - name: Package artefacts
        run: |
          for file in builds/*; do
            tar -czvf builds/$(basename "$file").tar.gz -C builds $(basename "$file")
          done
          ls -lisa builds

      - name: Upload tarballs
        run: |
          ls -lisa builds
          for tarball in builds/*.tar.gz; do
            gh release upload ${{ env.VERSION }} "$tarball" --repo mogenius/homebrew-punq
          done
        env:
          GH_TOKEN: ${{ secrets.PUNQ_TOKEN }}

      - name: UPDATE BREW
        run: |
          ./release.sh
          git config --global user.email "mogenius-cli@mogenius.com"
          git config --global user.name "mogenius-cli"
          git config --global credential.helper cache
          git clone https://${{secrets.PUNQ_TOKEN}}@github.com/mogenius/homebrew-punq
          cd homebrew-punq
          cp ../punq.rb .
          git add .
          git commit -m "${{ env.VERSION }}"
          git push
        env:
          GH_TOKEN: ${{ secrets.PUNQ_TOKEN }}